export const rooms = [
 { id: "1", label: "RD", color: "#b30000", topPct: 15, leftPct: 32, widthPct: 10, heightPct: 8, doctor: "Dr. Ayesha" },
  { id: "2", label: "CF", color: "#00b33c", topPct: 15, leftPct: 45, widthPct: 10, heightPct: 8, doctor: "Dr. Ahmad" },
  { id: "3/4", label: "DCT", color: "#0066cc", topPct: 15, leftPct: 59, widthPct: 13, heightPct: 8, doctor: "Dr. Hamza" },
  { id: "5", topPct: 15, leftPct: 57, widthPct: 10, heightPct: 8, doctor: "Dr. Sana" },
  { id: "6", topPct: 27, leftPct: 57, widthPct: 10, heightPct: 6, doctor: "Dr. Ali" },
  { id: "7", topPct: 34, leftPct: 57, widthPct: 10, heightPct: 6, doctor: "Dr. Sarah" },
  { id: "8", topPct: 41, leftPct: 57, widthPct: 10, heightPct: 6, doctor: "Dr. Kamran" },
  { id: "T1", topPct: 27, leftPct: 70, widthPct: 10, heightPct: 6, doctor: "Dr. Zeeshan" },
  { id: "T2", topPct: 34, leftPct: 70, widthPct: 10, heightPct: 6, doctor: "Dr. Bilal" },
  { id: "T3", topPct: 41, leftPct: 70, widthPct: 10, heightPct: 6, doctor: "Dr. Zain" },
  { id: "9", topPct: 75, leftPct: 57, widthPct: 10, heightPct: 8, doctor: "Dr. Iqra" },
  { id: "10", topPct: 75, leftPct: 45, widthPct: 10, heightPct: 8, doctor: "Dr. Adnan" },
  { id: "11", topPct: 75, leftPct: 38, widthPct: 10, heightPct: 8, doctor: "Dr. Saad" },
  { id: "12", topPct: 45, leftPct: 40, widthPct: 15, heightPct: 15, doctor: "Dr. Fatima" },
  { id: "13", topPct: 75, leftPct: 25, widthPct: 10, heightPct: 8, doctor: "Dr. Maryam" },
  { id: "14", topPct: 75, leftPct: 15, widthPct: 10, heightPct: 8, doctor: "Dr. Imran" },
  { id: "15", topPct: 75, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Javed" },
  { id: "16", topPct: 60, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Bushra" },
  { id: "17", topPct: 50, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Asif" },
  { id: "18", topPct: 40, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Anum" },
  { id: "19", topPct: 30, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Qasim" },
  { id: "20", topPct: 20, leftPct: 5, widthPct: 10, heightPct: 8, doctor: "Dr. Talha" },
];